import knex from 'knex';

export async function seed(knex: knex.Knex) {
    await knex('cidade').insert([
        { id: 1, nome: 'Afonso Cláudio', uf_id: 8 },
        { id: 2, nome: 'Água Doce do Norte', uf_id: 8 },
        { id: 3, nome: 'Águia Branca', uf_id: 8 },
        { id: 4, nome: 'Alegre', uf_id: 8 },
        { id: 5, nome: 'Alfredo Chaves', uf_id: 8 },
        { id: 6, nome: 'Alto Rio Novo', uf_id: 8 },
        { id: 7, nome: 'Anchieta', uf_id: 8 },
        { id: 8, nome: 'Apiacá', uf_id: 8 },
        { id: 9, nome: 'Aracruz', uf_id: 8 },
        { id: 10, nome: 'Atilio Vivacqua', uf_id: 8 },
        { id: 11, nome: 'Baixo Guandu', uf_id: 8 },
        { id: 12, nome: 'Barra de São Francisco', uf_id: 8 },
        { id: 13, nome: 'Boa Esperança', uf_id: 8 },
        { id: 14, nome: 'Bom Jesus do Norte', uf_id: 8 },
        { id: 15, nome: 'Brejetuba', uf_id: 8 },
        { id: 16, nome: 'Cachoeiro de Itapemirim', uf_id: 8 },
        { id: 17, nome: 'Cariacica', uf_id: 8 },
        { id: 18, nome: 'Castelo', uf_id: 8 },
        { id: 19, nome: 'Colatina', uf_id: 8 },
        { id: 20, nome: 'Conceição da Barra', uf_id: 8 },
        { id: 21, nome: 'Conceição do Castelo', uf_id: 8 },
        { id: 22, nome: 'Divino de São Lourenço', uf_id: 8 },
        { id: 23, nome: 'Domingos Martins', uf_id: 8 },
        { id: 24, nome: 'Dores do Rio Preto', uf_id: 8 },
        { id: 25, nome: 'Ecoporanga', uf_id: 8 },
        { id: 26, nome: 'Fundão', uf_id: 8 },
        { id: 27, nome: 'Governador Lindenberg', uf_id: 8 },
        { id: 28, nome: 'Guaçuí', uf_id: 8 },
        { id: 29, nome: 'Guarapari', uf_id: 8 },
        { id: 30, nome: 'Ibatiba', uf_id: 8 },
        { id: 31, nome: 'Ibiraçu', uf_id: 8 },
        { id: 32, nome: 'Ibitirama', uf_id: 8 },
        { id: 33, nome: 'Iconha', uf_id: 8 },
        { id: 34, nome: 'Irupi', uf_id: 8 },
        { id: 35, nome: 'Itaguaçu', uf_id: 8 },
        { id: 36, nome: 'Itapemirim', uf_id: 8 },
        { id: 37, nome: 'Itarana', uf_id: 8 },
        { id: 38, nome: 'Iúna', uf_id: 8 },
        { id: 39, nome: 'Jaguaré', uf_id: 8 },
        { id: 40, nome: 'Jerônimo Monteiro', uf_id: 8 },
        { id: 41, nome: 'João Neiva', uf_id: 8 },
        { id: 42, nome: 'Laranja da Terra', uf_id: 8 },
        { id: 43, nome: 'Linhares', uf_id: 8 },
        { id: 44, nome: 'Mantenópolis', uf_id: 8 },
        { id: 45, nome: 'Marataízes', uf_id: 8 },
        { id: 46, nome: 'Marechal Floriano', uf_id: 8 },
        { id: 47, nome: 'Marilândia', uf_id: 8 },
        { id: 48, nome: 'Mimoso do Sul', uf_id: 8 },
        { id: 49, nome: 'Montanha', uf_id: 8 },
        { id: 50, nome: 'Mucurici', uf_id: 8 },
        { id: 51, nome: 'Muniz Freire', uf_id: 8 },
        { id: 52, nome: 'Muqui', uf_id: 8 },
        { id: 53, nome: 'Nova Venécia', uf_id: 8 },
        { id: 54, nome: 'Pancas', uf_id: 8 },
        { id: 55, nome: 'Pedro Canário', uf_id: 8 },
        { id: 56, nome: 'Pinheiros', uf_id: 8 },
        { id: 57, nome: 'Piúma', uf_id: 8 },
        { id: 58, nome: 'Ponto Belo', uf_id: 8 },
        { id: 59, nome: 'Presidente Kennedy', uf_id: 8 },
        { id: 60, nome: 'Rio Bananal', uf_id: 8 },
        { id: 61, nome: 'Rio Novo do Sul', uf_id: 8 },
        { id: 62, nome: 'Santa Leopoldina', uf_id: 8 },
        { id: 63, nome: 'Santa Maria de Jetibá', uf_id: 8 },
        { id: 64, nome: 'Santa Teresa', uf_id: 8 },
        { id: 65, nome: 'São Domingos do Norte', uf_id: 8 },
        { id: 66, nome: 'São Gabriel da Palha', uf_id: 8 },
        { id: 67, nome: 'São José do Calçado', uf_id: 8 },
        { id: 68, nome: 'São Mateus', uf_id: 8 },
        { id: 69, nome: 'São Roque do Canaã', uf_id: 8 },
        { id: 70, nome: 'Serra', uf_id: 8 },
        { id: 71, nome: 'Sooretama', uf_id: 8 },
        { id: 72, nome: 'Vargem Alta', uf_id: 8 },
        { id: 73, nome: 'Venda Nova do Imigrante', uf_id: 8 },
        { id: 74, nome: 'Viana', uf_id: 8 },
        { id: 75, nome: 'Vila Pavão', uf_id: 8 },
        { id: 76, nome: 'Vila Valério', uf_id: 8 },
        { id: 77, nome: 'Vila Velha', uf_id: 8 },
        { id: 78, nome: 'Vitória', uf_id: 8 },
        { id: 79, nome: 'Acrelândia', uf_id: 1 },
        { id: 80, nome: 'Assis Brasil', uf_id: 1 },
        { id: 81, nome: 'Brasiléia', uf_id: 1 },
        { id: 82, nome: 'Bujari', uf_id: 1 },
        { id: 83, nome: 'Capixaba', uf_id: 1 },
        { id: 84, nome: 'Cruzeiro do Sul', uf_id: 1 },
        { id: 85, nome: 'Epitaciolândia', uf_id: 1 },
        { id: 86, nome: 'Feijó', uf_id: 1 },
        { id: 87, nome: 'Jordão', uf_id: 1 },
        { id: 88, nome: 'Mâncio Lima', uf_id: 1 },
        { id: 89, nome: 'Manoel Urbano', uf_id: 1 },
        { id: 90, nome: 'Marechal Thaumaturgo', uf_id: 1 },
        { id: 91, nome: 'Plácido de Castro', uf_id: 1 },
        { id: 92, nome: 'Porto Acre', uf_id: 1 },
        { id: 93, nome: 'Porto Walter', uf_id: 1 },
        { id: 94, nome: 'Rio Branco', uf_id: 1 },
        { id: 95, nome: 'Rodrigues Alves', uf_id: 1 },
        { id: 96, nome: 'Santa Rosa do Purus', uf_id: 1 },
        { id: 97, nome: 'Sena Madureira', uf_id: 1 },
        { id: 98, nome: 'Senador Guiomard', uf_id: 1 },
        { id: 99, nome: 'Tarauacá', uf_id: 1 },
        { id: 100, nome: 'Xapuri', uf_id: 1 },
        { id: 101, nome: 'Água Branca', uf_id: 2 },
        { id: 102, nome: 'Anadia', uf_id: 2 },
        { id: 103, nome: 'Arapiraca', uf_id: 2 },
        { id: 104, nome: 'Atalaia', uf_id: 2 },
        { id: 105, nome: 'Barra de Santo Antônio', uf_id: 2 },
        { id: 106, nome: 'Barra de São Miguel', uf_id: 2 },
        { id: 107, nome: 'Batalha', uf_id: 2 },
        { id: 108, nome: 'Belém', uf_id: 2 },
        { id: 109, nome: 'Belo Monte', uf_id: 2 },
        { id: 110, nome: 'Boca da Mata', uf_id: 2 },
        { id: 111, nome: 'Branquinha', uf_id: 2 },
        { id: 112, nome: 'Cacimbinhas', uf_id: 2 },
        { id: 113, nome: 'Cajueiro', uf_id: 2 },
        { id: 114, nome: 'Campestre', uf_id: 2 },
        { id: 115, nome: 'Campo Alegre', uf_id: 2 },
        { id: 116, nome: 'Campo Grande', uf_id: 2 },
        { id: 117, nome: 'Canapi', uf_id: 2 },
        { id: 118, nome: 'Capela', uf_id: 2 },
        { id: 119, nome: 'Carneiros', uf_id: 2 },
        { id: 120, nome: 'Chã Preta', uf_id: 2 },
        { id: 121, nome: 'Coité do Nóia', uf_id: 2 },
        { id: 122, nome: 'Colônia Leopoldina', uf_id: 2 },
        { id: 123, nome: 'Coqueiro Seco', uf_id: 2 },
        { id: 124, nome: 'Coruripe', uf_id: 2 },
        { id: 125, nome: 'Craíbas', uf_id: 2 },
        { id: 126, nome: 'Delmiro Gouveia', uf_id: 2 },
        { id: 127, nome: 'Dois Riachos', uf_id: 2 },
        { id: 128, nome: 'Estrela de Alagoas', uf_id: 2 },
        { id: 129, nome: 'Feira Grande', uf_id: 2 },
        { id: 130, nome: 'Feliz Deserto', uf_id: 2 },
        { id: 131, nome: 'Flexeiras', uf_id: 2 },
        { id: 132, nome: 'Girau do Ponciano', uf_id: 2 },
        { id: 133, nome: 'Ibateguara', uf_id: 2 },
        { id: 134, nome: 'Igaci', uf_id: 2 },
        { id: 135, nome: 'Igreja Nova', uf_id: 2 },
        { id: 136, nome: 'Inhapi', uf_id: 2 },
        { id: 137, nome: 'Jacaré dos Homens', uf_id: 2 },
        { id: 138, nome: 'Jacuípe', uf_id: 2 },
        { id: 139, nome: 'Japaratinga', uf_id: 2 },
        { id: 140, nome: 'Jaramataia', uf_id: 2 },
        { id: 141, nome: 'Jequiá da Praia', uf_id: 2 },
        { id: 142, nome: 'Joaquim Gomes', uf_id: 2 },
        { id: 143, nome: 'Jundiá', uf_id: 2 },
        { id: 144, nome: 'Junqueiro', uf_id: 2 },
        { id: 145, nome: 'Lagoa da Canoa', uf_id: 2 },
        { id: 146, nome: 'Limoeiro de Anadia', uf_id: 2 },
        { id: 147, nome: 'Maceió', uf_id: 2 },
        { id: 148, nome: 'Major Isidoro', uf_id: 2 },
        { id: 149, nome: 'Mar Vermelho', uf_id: 2 },
        { id: 150, nome: 'Maragogi', uf_id: 2 },
        { id: 151, nome: 'Maravilha', uf_id: 2 },
        { id: 152, nome: 'Marechal Deodoro', uf_id: 2 },
        { id: 153, nome: 'Maribondo', uf_id: 2 },
        { id: 154, nome: 'Mata Grande', uf_id: 2 },
        { id: 155, nome: 'Matriz de Camaragibe', uf_id: 2 },
        { id: 156, nome: 'Messias', uf_id: 2 },
        { id: 157, nome: 'Minador do Negrão', uf_id: 2 },
        { id: 158, nome: 'Monteirópolis', uf_id: 2 },
        { id: 159, nome: 'Murici', uf_id: 2 },
        { id: 160, nome: 'Novo Lino', uf_id: 2 },
        { id: 161, nome: 'Olho d`Água das Flores', uf_id: 2 },
        { id: 162, nome: 'Olho d`Água do Casado', uf_id: 2 },
        { id: 163, nome: 'Olho d`Água Grande', uf_id: 2 },
        { id: 164, nome: 'Olivença', uf_id: 2 },
        { id: 165, nome: 'Ouro Branco', uf_id: 2 },
        { id: 166, nome: 'Palestina', uf_id: 2 },
        { id: 167, nome: 'Palmeira dos Índios', uf_id: 2 },
        { id: 168, nome: 'Pão de Açúcar', uf_id: 2 },
        { id: 169, nome: 'Pariconha', uf_id: 2 },
        { id: 170, nome: 'Paripueira', uf_id: 2 },
        { id: 171, nome: 'Passo de Camaragibe', uf_id: 2 },
        { id: 172, nome: 'Paulo Jacinto', uf_id: 2 },
        { id: 173, nome: 'Penedo', uf_id: 2 },
        { id: 174, nome: 'Piaçabuçu', uf_id: 2 },
        { id: 175, nome: 'Pilar', uf_id: 2 },
        { id: 176, nome: 'Pindoba', uf_id: 2 },
        { id: 177, nome: 'Piranhas', uf_id: 2 },
        { id: 178, nome: 'Poço das Trincheiras', uf_id: 2 },
        { id: 179, nome: 'Porto Calvo', uf_id: 2 },
        { id: 180, nome: 'Porto de Pedras', uf_id: 2 },
        { id: 181, nome: 'Porto Real do Colégio', uf_id: 2 },
        { id: 182, nome: 'Quebrangulo', uf_id: 2 },
        { id: 183, nome: 'Rio Largo', uf_id: 2 },
        { id: 184, nome: 'Roteiro', uf_id: 2 },
        { id: 185, nome: 'Santa Luzia do Norte', uf_id: 2 },
        { id: 186, nome: 'Santana do Ipanema', uf_id: 2 },
        { id: 187, nome: 'Santana do Mundaú', uf_id: 2 },
        { id: 188, nome: 'São Brás', uf_id: 2 },
        { id: 189, nome: 'São José da Laje', uf_id: 2 },
        { id: 190, nome: 'São José da Tapera', uf_id: 2 },
        { id: 191, nome: 'São Luís do Quitunde', uf_id: 2 },
        { id: 192, nome: 'São Miguel dos Campos', uf_id: 2 },
        { id: 193, nome: 'São Miguel dos Milagres', uf_id: 2 },
        { id: 194, nome: 'São Sebastião', uf_id: 2 },
        { id: 195, nome: 'Satuba', uf_id: 2 },
        { id: 196, nome: 'Senador Rui Palmeira', uf_id: 2 },
        { id: 197, nome: 'Tanque d`Arca', uf_id: 2 },
        { id: 198, nome: 'Taquarana', uf_id: 2 },
        { id: 199, nome: 'Teotônio Vilela', uf_id: 2 },
        { id: 200, nome: 'Traipu', uf_id: 2 },
        { id: 201, nome: 'União dos Palmares', uf_id: 2 },
        { id: 202, nome: 'Viçosa', uf_id: 2 },
        { id: 203, nome: 'Amapá', uf_id: 4 },
        { id: 204, nome: 'Calçoene', uf_id: 4 },
        { id: 205, nome: 'Cutias', uf_id: 4 },
        { id: 206, nome: 'Ferreira Gomes', uf_id: 4 },
        { id: 207, nome: 'Itaubal', uf_id: 4 },
        { id: 208, nome: 'Laranjal do Jari', uf_id: 4 },
        { id: 209, nome: 'Macapá', uf_id: 4 },
        { id: 210, nome: 'Mazagão', uf_id: 4 },
        { id: 211, nome: 'Oiapoque', uf_id: 4 },
        { id: 212, nome: 'Pedra Branca do Amaparí', uf_id: 4 },
        { id: 213, nome: 'Porto Grande', uf_id: 4 },
        { id: 214, nome: 'Pracuúba', uf_id: 4 },
        { id: 215, nome: 'Santana', uf_id: 4 },
        { id: 216, nome: 'Serra do Navio', uf_id: 4 },
        { id: 217, nome: 'Tartarugalzinho', uf_id: 4 },
        { id: 218, nome: 'Vitória do Jari', uf_id: 4 },
        { id: 219, nome: 'Alvarães', uf_id: 3 },
        { id: 220, nome: 'Amaturá', uf_id: 3 },
        { id: 221, nome: 'Anamã', uf_id: 3 },
        { id: 222, nome: 'Anori', uf_id: 3 },
        { id: 223, nome: 'Apuí', uf_id: 3 },
        { id: 224, nome: 'Atalaia do Norte', uf_id: 3 },
        { id: 225, nome: 'Autazes', uf_id: 3 },
        { id: 226, nome: 'Barcelos', uf_id: 3 },
        { id: 227, nome: 'Barreirinha', uf_id: 3 },
        { id: 228, nome: 'Benjamin Constant', uf_id: 3 },
        { id: 229, nome: 'Beruri', uf_id: 3 },
        { id: 230, nome: 'Boa Vista do Ramos', uf_id: 3 },
        { id: 231, nome: 'Boca do Acre', uf_id: 3 },
        { id: 232, nome: 'Borba', uf_id: 3 },
        { id: 233, nome: 'Caapiranga', uf_id: 3 },
        { id: 234, nome: 'Canutama', uf_id: 3 },
        { id: 235, nome: 'Carauari', uf_id: 3 },
        { id: 236, nome: 'Careiro', uf_id: 3 },
        { id: 237, nome: 'Careiro da Várzea', uf_id: 3 },
        { id: 238, nome: 'Coari', uf_id: 3 },
        { id: 239, nome: 'Codajás', uf_id: 3 },
        { id: 240, nome: 'Eirunepé', uf_id: 3 },
        { id: 241, nome: 'Envira', uf_id: 3 },
        { id: 242, nome: 'Fonte Boa', uf_id: 3 },
        { id: 243, nome: 'Guajará', uf_id: 3 },
        { id: 244, nome: 'Humaitá', uf_id: 3 },
        { id: 245, nome: 'Ipixuna', uf_id: 3 },
        { id: 246, nome: 'Iranduba', uf_id: 3 },
        { id: 247, nome: 'Itacoatiara', uf_id: 3 },
        { id: 248, nome: 'Itamarati', uf_id: 3 },
        { id: 249, nome: 'Itapiranga', uf_id: 3 },
        { id: 250, nome: 'Japurá', uf_id: 3 },
        { id: 251, nome: 'Juruá', uf_id: 3 },
        { id: 252, nome: 'Jutaí', uf_id: 3 },
        { id: 253, nome: 'Lábrea', uf_id: 3 },
        { id: 254, nome: 'Manacapuru', uf_id: 3 },
        { id: 255, nome: 'Manaquiri', uf_id: 3 },
        { id: 256, nome: 'Manaus', uf_id: 3 },
        { id: 257, nome: 'Manicoré', uf_id: 3 },
        { id: 258, nome: 'Maraã', uf_id: 3 },
        { id: 259, nome: 'Maués', uf_id: 3 },
        { id: 260, nome: 'Nhamundá', uf_id: 3 },
        { id: 261, nome: 'Nova Olinda do Norte', uf_id: 3 },
        { id: 262, nome: 'Novo Airão', uf_id: 3 },
        { id: 263, nome: 'Novo Aripuanã', uf_id: 3 },
        { id: 264, nome: 'Parintins', uf_id: 3 },
        { id: 265, nome: 'Pauini', uf_id: 3 },
        { id: 266, nome: 'Presidente Figueiredo', uf_id: 3 },
        { id: 267, nome: 'Rio Preto da Eva', uf_id: 3 },
        { id: 268, nome: 'Santa Isabel do Rio Negro', uf_id: 3 },
        { id: 269, nome: 'Santo Antônio do Içá', uf_id: 3 },
        { id: 270, nome: 'São Gabriel da Cachoeira', uf_id: 3 },
        { id: 271, nome: 'São Paulo de Olivença', uf_id: 3 },
        { id: 272, nome: 'São Sebastião do Uatumã', uf_id: 3 },
        { id: 273, nome: 'Silves', uf_id: 3 },
        { id: 274, nome: 'Tabatinga', uf_id: 3 },
        { id: 275, nome: 'Tapauá', uf_id: 3 },
        { id: 276, nome: 'Tefé', uf_id: 3 },
        { id: 277, nome: 'Tonantins', uf_id: 3 },
        { id: 278, nome: 'Uarini', uf_id: 3 },
        { id: 279, nome: 'Urucará', uf_id: 3 },
        { id: 280, nome: 'Urucurituba', uf_id: 3 },
        { id: 281, nome: 'Abaíra', uf_id: 5 },
        { id: 282, nome: 'Abaré', uf_id: 5 },
        { id: 283, nome: 'Acajutiba', uf_id: 5 },
        { id: 284, nome: 'Adustina', uf_id: 5 },
        { id: 285, nome: 'Água Fria', uf_id: 5 },
        { id: 286, nome: 'Aiquara', uf_id: 5 },
        { id: 287, nome: 'Alagoinhas', uf_id: 5 },
        { id: 288, nome: 'Alcobaça', uf_id: 5 },
        { id: 289, nome: 'Almadina', uf_id: 5 },
        { id: 290, nome: 'Amargosa', uf_id: 5 },
        { id: 291, nome: 'Amélia Rodrigues', uf_id: 5 },
        { id: 292, nome: 'América Dourada', uf_id: 5 },
        { id: 293, nome: 'Anagé', uf_id: 5 },
        { id: 294, nome: 'Andaraí', uf_id: 5 },
        { id: 295, nome: 'Andorinha', uf_id: 5 },
        { id: 296, nome: 'Angical', uf_id: 5 },
        { id: 297, nome: 'Anguera', uf_id: 5 },
        { id: 298, nome: 'Antas', uf_id: 5 },
        { id: 299, nome: 'Antônio Cardoso', uf_id: 5 },
        { id: 300, nome: 'Antônio Gonçalves', uf_id: 5 },
        { id: 301, nome: 'Aporá', uf_id: 5 },
        { id: 302, nome: 'Apuarema', uf_id: 5 },
        { id: 303, nome: 'Araças', uf_id: 5 },
        { id: 304, nome: 'Aracatu', uf_id: 5 },
        { id: 305, nome: 'Araci', uf_id: 5 },
        { id: 306, nome: 'Aramari', uf_id: 5 },
        { id: 307, nome: 'Arataca', uf_id: 5 },
        { id: 308, nome: 'Aratuípe', uf_id: 5 },
        { id: 309, nome: 'Aurelino Leal', uf_id: 5 },
        { id: 310, nome: 'Baianópolis', uf_id: 5 },
        { id: 311, nome: 'Baixa Grande', uf_id: 5 },
        { id: 312, nome: 'Banzaê', uf_id: 5 },
        { id: 313, nome: 'Barra', uf_id: 5 },
        { id: 314, nome: 'Barra da Estiva', uf_id: 5 },
        { id: 315, nome: 'Barra do Choça', uf_id: 5 },
        { id: 316, nome: 'Barra do Mendes', uf_id: 5 },
        { id: 317, nome: 'Barra do Rocha', uf_id: 5 },
        { id: 318, nome: 'Barreiras', uf_id: 5 },
        { id: 319, nome: 'Barro Alto', uf_id: 5 },
        { id: 320, nome: 'Barro Preto (antigo Gov. Lomanto Jr.)', uf_id: 5 },
        { id: 321, nome: 'Barrocas', uf_id: 5 },
        { id: 322, nome: 'Belmonte', uf_id: 5 },
        { id: 323, nome: 'Belo Campo', uf_id: 5 },
        { id: 324, nome: 'Biritinga', uf_id: 5 },
        { id: 325, nome: 'Boa Nova', uf_id: 5 },
        { id: 326, nome: 'Boa Vista do Tupim', uf_id: 5 },
        { id: 327, nome: 'Bom Jesus da Lapa', uf_id: 5 },
        { id: 328, nome: 'Bom Jesus da Serra', uf_id: 5 },
        { id: 329, nome: 'Boninal', uf_id: 5 },
        { id: 330, nome: 'Bonito', uf_id: 5 },
        { id: 331, nome: 'Boquira', uf_id: 5 },
        { id: 332, nome: 'Botuporã', uf_id: 5 },
        { id: 333, nome: 'Brejões', uf_id: 5 },
        { id: 334, nome: 'Brejolândia', uf_id: 5 },
        { id: 335, nome: 'Brotas de Macaúbas', uf_id: 5 },
        { id: 336, nome: 'Brumado', uf_id: 5 },
        { id: 337, nome: 'Buerarema', uf_id: 5 },
        { id: 338, nome: 'Buritirama', uf_id: 5 },
        { id: 339, nome: 'Caatiba', uf_id: 5 },
        { id: 340, nome: 'Cabaceiras do Paraguaçu', uf_id: 5 },
        { id: 341, nome: 'Cachoeira', uf_id: 5 },
        { id: 342, nome: 'Caculé', uf_id: 5 },
        { id: 343, nome: 'Caém', uf_id: 5 },
        { id: 344, nome: 'Caetanos', uf_id: 5 },
        { id: 345, nome: 'Caetité', uf_id: 5 },
        { id: 346, nome: 'Cafarnaum', uf_id: 5 },
        { id: 347, nome: 'Cairu', uf_id: 5 },
        { id: 348, nome: 'Caldeirão Grande', uf_id: 5 },
        { id: 349, nome: 'Camacan', uf_id: 5 },
        { id: 350, nome: 'Camaçari', uf_id: 5 },
        { id: 351, nome: 'Camamu', uf_id: 5 },
        { id: 352, nome: 'Campo Alegre de Lourdes', uf_id: 5 },
        { id: 353, nome: 'Campo Formoso', uf_id: 5 },
        { id: 354, nome: 'Canápolis', uf_id: 5 },
        { id: 355, nome: 'Canarana', uf_id: 5 },
        { id: 356, nome: 'Canavieiras', uf_id: 5 },
        { id: 357, nome: 'Candeal', uf_id: 5 },
        { id: 358, nome: 'Candeias', uf_id: 5 },
        { id: 359, nome: 'Candiba', uf_id: 5 },
        { id: 360, nome: 'Cândido Sales', uf_id: 5 },
        { id: 361, nome: 'Cansanção', uf_id: 5 },
        { id: 362, nome: 'Canudos', uf_id: 5 },
        { id: 363, nome: 'Capela do Alto Alegre', uf_id: 5 },
        { id: 364, nome: 'Capim Grosso', uf_id: 5 },
        { id: 365, nome: 'Caraíbas', uf_id: 5 },
        { id: 366, nome: 'Caravelas', uf_id: 5 },
        { id: 367, nome: 'Cardeal da Silva', uf_id: 5 },
        { id: 368, nome: 'Carinhanha', uf_id: 5 },
        { id: 369, nome: 'Casa Nova', uf_id: 5 },
        { id: 370, nome: 'Castro Alves', uf_id: 5 },
        { id: 371, nome: 'Catolândia', uf_id: 5 },
        { id: 372, nome: 'Catu', uf_id: 5 },
        { id: 373, nome: 'Caturama', uf_id: 5 },
        { id: 374, nome: 'Central', uf_id: 5 },
        { id: 375, nome: 'Chorrochó', uf_id: 5 },
        { id: 376, nome: 'Cícero Dantas', uf_id: 5 },
        { id: 377, nome: 'Cipó', uf_id: 5 },
        { id: 378, nome: 'Coaraci', uf_id: 5 },
        { id: 379, nome: 'Cocos', uf_id: 5 },
        { id: 380, nome: 'Conceição da Feira', uf_id: 5 },
        { id: 381, nome: 'Conceição do Almeida', uf_id: 5 },
        { id: 382, nome: 'Conceição do Coité', uf_id: 5 },
        { id: 383, nome: 'Conceição do Jacuípe', uf_id: 5 },
        { id: 384, nome: 'Conde', uf_id: 5 },
        { id: 385, nome: 'Condeúba', uf_id: 5 },
        { id: 386, nome: 'Contendas do Sincorá', uf_id: 5 },
        { id: 387, nome: 'Coração de Maria', uf_id: 5 },
        { id: 388, nome: 'Cordeiros', uf_id: 5 },
        { id: 389, nome: 'Coribe', uf_id: 5 },
        { id: 390, nome: 'Coronel João Sá', uf_id: 5 },
        { id: 391, nome: 'Correntina', uf_id: 5 },
        { id: 392, nome: 'Cotegipe', uf_id: 5 },
        { id: 393, nome: 'Cravolândia', uf_id: 5 },
        { id: 394, nome: 'Crisópolis', uf_id: 5 },
        { id: 395, nome: 'Cristópolis', uf_id: 5 },
        { id: 396, nome: 'Cruz das Almas', uf_id: 5 },
        { id: 397, nome: 'Curaçá', uf_id: 5 },
        { id: 398, nome: 'Dário Meira', uf_id: 5 },
        { id: 399, nome: 'Dias d`Ávila', uf_id: 5 },
        { id: 400, nome: 'Dom Basílio', uf_id: 5 },
        { id: 401, nome: 'Dom Macedo Costa', uf_id: 5 },
        { id: 402, nome: 'Elísio Medrado', uf_id: 5 },
        { id: 403, nome: 'Encruzilhada', uf_id: 5 },
        { id: 404, nome: 'Entre Rios', uf_id: 5 },
        { id: 405, nome: 'Érico Cardoso', uf_id: 5 },
        { id: 406, nome: 'Esplanada', uf_id: 5 },
        { id: 407, nome: 'Euclides da Cunha', uf_id: 5 },
        { id: 408, nome: 'Eunápolis', uf_id: 5 },
        { id: 409, nome: 'Fátima', uf_id: 5 },
        { id: 410, nome: 'Feira da Mata', uf_id: 5 },
        { id: 411, nome: 'Feira de Santana', uf_id: 5 },
        { id: 412, nome: 'Filadélfia', uf_id: 5 },
        { id: 413, nome: 'Firmino Alves', uf_id: 5 },
        { id: 414, nome: 'Floresta Azul', uf_id: 5 },
        { id: 415, nome: 'Formosa do Rio Preto', uf_id: 5 },
        { id: 416, nome: 'Gandu', uf_id: 5 },
        { id: 417, nome: 'Gavião', uf_id: 5 },
        { id: 418, nome: 'Gentio do Ouro', uf_id: 5 },
        { id: 419, nome: 'Glória', uf_id: 5 },
        { id: 420, nome: 'Gongogi', uf_id: 5 },
        { id: 421, nome: 'Governador Mangabeira', uf_id: 5 },
        { id: 422, nome: 'Guajeru', uf_id: 5 },
        { id: 423, nome: 'Guanambi', uf_id: 5 },
        { id: 424, nome: 'Guaratinga', uf_id: 5 },
        { id: 425, nome: 'Heliópolis', uf_id: 5 },
        { id: 426, nome: 'Iaçu', uf_id: 5 },
        { id: 427, nome: 'Ibiassucê', uf_id: 5 },
        { id: 428, nome: 'Ibicaraí', uf_id: 5 },
        { id: 429, nome: 'Ibicoara', uf_id: 5 },
        { id: 430, nome: 'Ibicuí', uf_id: 5 },
        { id: 431, nome: 'Ibipeba', uf_id: 5 },
        { id: 432, nome: 'Ibipitanga', uf_id: 5 },
        { id: 433, nome: 'Ibiquera', uf_id: 5 },
        { id: 434, nome: 'Ibirapitanga', uf_id: 5 },
        { id: 435, nome: 'Ibirapuã', uf_id: 5 },
        { id: 436, nome: 'Ibirataia', uf_id: 5 },
        { id: 437, nome: 'Ibitiara', uf_id: 5 },
        { id: 438, nome: 'Ibititá', uf_id: 5 },
        { id: 439, nome: 'Ibotirama', uf_id: 5 },
        { id: 440, nome: 'Ichu', uf_id: 5 },
        { id: 441, nome: 'Igaporã', uf_id: 5 },
        { id: 442, nome: 'Igrapiúna', uf_id: 5 },
        { id: 443, nome: 'Iguaí', uf_id: 5 },
        { id: 444, nome: 'Ilhéus', uf_id: 5 },
        { id: 445, nome: 'Inhambupe', uf_id: 5 },
        { id: 446, nome: 'Ipecaetá', uf_id: 5 },
        { id: 447, nome: 'Ipiaú', uf_id: 5 },
        { id: 448, nome: 'Ipirá', uf_id: 5 },
        { id: 449, nome: 'Ipupiara', uf_id: 5 },
        { id: 450, nome: 'Irajuba', uf_id: 5 },
        { id: 451, nome: 'Iramaia', uf_id: 5 },
        { id: 452, nome: 'Iraquara', uf_id: 5 },
        { id: 453, nome: 'Irará', uf_id: 5 },
        { id: 454, nome: 'Irecê', uf_id: 5 },
        { id: 455, nome: 'Itabela', uf_id: 5 },
        { id: 456, nome: 'Itaberaba', uf_id: 5 },
        { id: 457, nome: 'Itabuna', uf_id: 5 },
        { id: 458, nome: 'Itacaré', uf_id: 5 },
        { id: 459, nome: 'Itaeté', uf_id: 5 },
        { id: 460, nome: 'Itagi', uf_id: 5 },
        { id: 461, nome: 'Itagibá', uf_id: 5 },
        { id: 462, nome: 'Itagimirim', uf_id: 5 },
        { id: 463, nome: 'Itaguaçu da Bahia', uf_id: 5 },
        { id: 464, nome: 'Itaju do Colônia', uf_id: 5 },
        { id: 465, nome: 'Itajuípe', uf_id: 5 },
        { id: 466, nome: 'Itamaraju', uf_id: 5 },
        { id: 467, nome: 'Itamari', uf_id: 5 },
        { id: 468, nome: 'Itambé', uf_id: 5 },
        { id: 469, nome: 'Itanagra', uf_id: 5 },
        { id: 470, nome: 'Itanhém', uf_id: 5 },
        { id: 471, nome: 'Itaparica', uf_id: 5 },
        { id: 472, nome: 'Itapé', uf_id: 5 },
        { id: 473, nome: 'Itapebi', uf_id: 5 },
        { id: 474, nome: 'Itapetinga', uf_id: 5 },
        { id: 475, nome: 'Itapicuru', uf_id: 5 },
        { id: 476, nome: 'Itapitanga', uf_id: 5 },
        { id: 477, nome: 'Itaquara', uf_id: 5 },
        { id: 478, nome: 'Itarantim', uf_id: 5 },
        { id: 479, nome: 'Itatim', uf_id: 5 },
        { id: 480, nome: 'Itiruçu', uf_id: 5 },
        { id: 481, nome: 'Itiúba', uf_id: 5 },
        { id: 482, nome: 'Itororó', uf_id: 5 },
        { id: 483, nome: 'Ituaçu', uf_id: 5 },
        { id: 484, nome: 'Ituberá', uf_id: 5 },
        { id: 485, nome: 'Iuiú', uf_id: 5 },
        { id: 486, nome: 'Jaborandi', uf_id: 5 },
        { id: 487, nome: 'Jacaraci', uf_id: 5 },
        { id: 488, nome: 'Jacobina', uf_id: 5 },
        { id: 489, nome: 'Jaguaquara', uf_id: 5 },
        { id: 490, nome: 'Jaguarari', uf_id: 5 },
        { id: 491, nome: 'Jaguaripe', uf_id: 5 },
        { id: 492, nome: 'Jandaíra', uf_id: 5 },
        { id: 493, nome: 'Jequié', uf_id: 5 },
        { id: 494, nome: 'Jeremoabo', uf_id: 5 },
        { id: 495, nome: 'Jiquiriçá', uf_id: 5 },
        { id: 496, nome: 'Jitaúna', uf_id: 5 },
        { id: 497, nome: 'João Dourado', uf_id: 5 },
        { id: 498, nome: 'Juazeiro', uf_id: 5 },
        { id: 499, nome: 'Jucuruçu', uf_id: 5 }
    ])
}