import knex from 'knex';

export async function seed(knex: knex.Knex) {
    await knex('cidade').insert([
        { id: 500, nome: 'Jussara', uf_id: 5 },
        { id: 501, nome: 'Jussari', uf_id: 5 },
        { id: 502, nome: 'Jussiape', uf_id: 5 },
        { id: 503, nome: 'Lafaiete Coutinho', uf_id: 5 },
        { id: 504, nome: 'Lagoa Real', uf_id: 5 },
        { id: 505, nome: 'Laje', uf_id: 5 },
        { id: 506, nome: 'Lajedão', uf_id: 5 },
        { id: 507, nome: 'Lajedinho', uf_id: 5 },
        { id: 508, nome: 'Lajedo do Tabocal', uf_id: 5 },
        { id: 509, nome: 'Lamarão', uf_id: 5 },
        { id: 510, nome: 'Lapão', uf_id: 5 },
        { id: 511, nome: 'Lauro de Freitas', uf_id: 5 },
        { id: 512, nome: 'Lençóis', uf_id: 5 },
        { id: 513, nome: 'Licínio de Almeida', uf_id: 5 },
        { id: 514, nome: 'Livramento de Nossa Senhora', uf_id: 5 },
        { id: 515, nome: 'Luís Eduardo Magalhães', uf_id: 5 },
        { id: 516, nome: 'Macajuba', uf_id: 5 },
        { id: 517, nome: 'Macarani', uf_id: 5 },
        { id: 518, nome: 'Macaúbas', uf_id: 5 },
        { id: 519, nome: 'Macururé', uf_id: 5 },
        { id: 520, nome: 'Madre de Deus', uf_id: 5 },
        { id: 521, nome: 'Maetinga', uf_id: 5 },
        { id: 522, nome: 'Maiquinique', uf_id: 5 },
        { id: 523, nome: 'Mairi', uf_id: 5 },
        { id: 524, nome: 'Malhada', uf_id: 5 },
        { id: 525, nome: 'Malhada de Pedras', uf_id: 5 },
        { id: 526, nome: 'Manoel Vitorino', uf_id: 5 },
        { id: 527, nome: 'Mansidão', uf_id: 5 },
        { id: 528, nome: 'Maracás', uf_id: 5 },
        { id: 529, nome: 'Maragogipe', uf_id: 5 },
        { id: 530, nome: 'Maraú', uf_id: 5 },
        { id: 531, nome: 'Marcionílio Souza', uf_id: 5 },
        { id: 532, nome: 'Mascote', uf_id: 5 },
        { id: 533, nome: 'Mata de São João', uf_id: 5 },
        { id: 534, nome: 'Matina', uf_id: 5 },
        { id: 535, nome: 'Medeiros Neto', uf_id: 5 },
        { id: 536, nome: 'Miguel Calmon', uf_id: 5 },
        { id: 537, nome: 'Milagres', uf_id: 5 },
        { id: 538, nome: 'Mirangaba', uf_id: 5 },
        { id: 539, nome: 'Mirante', uf_id: 5 },
        { id: 540, nome: 'Monte Santo', uf_id: 5 },
        { id: 541, nome: 'Morpará', uf_id: 5 },
        { id: 542, nome: 'Morro do Chapéu', uf_id: 5 },
        { id: 543, nome: 'Mortugaba', uf_id: 5 },
        { id: 544, nome: 'Mucugê', uf_id: 5 },
        { id: 545, nome: 'Mucuri', uf_id: 5 },
        { id: 546, nome: 'Mulungu do Morro', uf_id: 5 },
        { id: 547, nome: 'Mundo Novo', uf_id: 5 },
        { id: 548, nome: 'Muniz Ferreira', uf_id: 5 },
        { id: 549, nome: 'Muquém de São Francisco', uf_id: 5 },
        { id: 550, nome: 'Muritiba', uf_id: 5 },
        { id: 551, nome: 'Mutuípe', uf_id: 5 },
        { id: 552, nome: 'Nazaré', uf_id: 5 },
        { id: 553, nome: 'Nilo Peçanha', uf_id: 5 },
        { id: 554, nome: 'Nordestina', uf_id: 5 },
        { id: 555, nome: 'Nova Canaã', uf_id: 5 },
        { id: 556, nome: 'Nova Fátima', uf_id: 5 },
        { id: 557, nome: 'Nova Ibiá', uf_id: 5 },
        { id: 558, nome: 'Nova Itarana', uf_id: 5 },
        { id: 559, nome: 'Nova Redenção', uf_id: 5 },
        { id: 560, nome: 'Nova Soure', uf_id: 5 },
        { id: 561, nome: 'Nova Viçosa', uf_id: 5 },
        { id: 562, nome: 'Novo Horizonte', uf_id: 5 },
        { id: 563, nome: 'Novo Triunfo', uf_id: 5 },
        { id: 564, nome: 'Olindina', uf_id: 5 },
        { id: 565, nome: 'Oliveira dos Brejinhos', uf_id: 5 },
        { id: 566, nome: 'Ouriçangas', uf_id: 5 },
        { id: 567, nome: 'Ourolândia', uf_id: 5 },
        { id: 568, nome: 'Palmas de Monte Alto', uf_id: 5 },
        { id: 569, nome: 'Palmeiras', uf_id: 5 },
        { id: 570, nome: 'Paramirim', uf_id: 5 },
        { id: 571, nome: 'Paratinga', uf_id: 5 },
        { id: 572, nome: 'Paripiranga', uf_id: 5 },
        { id: 573, nome: 'Pau Brasil', uf_id: 5 },
        { id: 574, nome: 'Paulo Afonso', uf_id: 5 },
        { id: 575, nome: 'Pé de Serra', uf_id: 5 },
        { id: 576, nome: 'Pedrão', uf_id: 5 },
        { id: 577, nome: 'Pedro Alexandre', uf_id: 5 },
        { id: 578, nome: 'Piatã', uf_id: 5 },
        { id: 579, nome: 'Pilão Arcado', uf_id: 5 },
        { id: 580, nome: 'Pindaí', uf_id: 5 },
        { id: 581, nome: 'Pindobaçu', uf_id: 5 },
        { id: 582, nome: 'Pintadas', uf_id: 5 },
        { id: 583, nome: 'Piraí do Norte', uf_id: 5 },
        { id: 584, nome: 'Piripá', uf_id: 5 },
        { id: 585, nome: 'Piritiba', uf_id: 5 },
        { id: 586, nome: 'Planaltino', uf_id: 5 },
        { id: 587, nome: 'Planalto', uf_id: 5 },
        { id: 588, nome: 'Poções', uf_id: 5 },
        { id: 589, nome: 'Pojuca', uf_id: 5 },
        { id: 590, nome: 'Ponto Novo', uf_id: 5 },
        { id: 591, nome: 'Porto Seguro', uf_id: 5 },
        { id: 592, nome: 'Potiraguá', uf_id: 5 },
        { id: 593, nome: 'Prado', uf_id: 5 },
        { id: 594, nome: 'Presidente Dutra', uf_id: 5 },
        { id: 595, nome: 'Presidente Jânio Quadros', uf_id: 5 },
        { id: 596, nome: 'Presidente Tancredo Neves', uf_id: 5 },
        { id: 597, nome: 'Queimadas', uf_id: 5 },
        { id: 598, nome: 'Quijingue', uf_id: 5 },
        { id: 599, nome: 'Quixabeira', uf_id: 5 },
        { id: 600, nome: 'Rafael Jambeiro', uf_id: 5 },
        { id: 601, nome: 'Remanso', uf_id: 5 },
        { id: 602, nome: 'Retirolândia', uf_id: 5 },
        { id: 603, nome: 'Riachão das Neves', uf_id: 5 },
        { id: 604, nome: 'Riachão do Jacuípe', uf_id: 5 },
        { id: 605, nome: 'Riacho de Santana', uf_id: 5 },
        { id: 606, nome: 'Ribeira do Amparo', uf_id: 5 },
        { id: 607, nome: 'Ribeira do Pombal', uf_id: 5 },
        { id: 608, nome: 'Ribeirão do Largo', uf_id: 5 },
        { id: 609, nome: 'Rio de Contas', uf_id: 5 },
        { id: 610, nome: 'Rio do Antônio', uf_id: 5 },
        { id: 611, nome: 'Rio do Pires', uf_id: 5 },
        { id: 612, nome: 'Rio Real', uf_id: 5 },
        { id: 613, nome: 'Rodelas', uf_id: 5 },
        { id: 614, nome: 'Ruy Barbosa', uf_id: 5 },
        { id: 615, nome: 'Salinas da Margarida', uf_id: 5 },
        { id: 616, nome: 'Salvador', uf_id: 5 },
        { id: 617, nome: 'Santa Bárbara', uf_id: 5 },
        { id: 618, nome: 'Santa Brígida', uf_id: 5 },
        { id: 619, nome: 'Santa Cruz Cabrália', uf_id: 5 },
        { id: 620, nome: 'Santa Cruz da Vitória', uf_id: 5 },
        { id: 621, nome: 'Santa Inês', uf_id: 5 },
        { id: 622, nome: 'Santa Luzia', uf_id: 5 },
        { id: 623, nome: 'Santa Maria da Vitória', uf_id: 5 },
        { id: 624, nome: 'Santa Rita de Cássia', uf_id: 5 },
        { id: 625, nome: 'Santa Teresinha', uf_id: 5 },
        { id: 626, nome: 'Santaluz', uf_id: 5 },
        { id: 627, nome: 'Santana', uf_id: 5 },
        { id: 628, nome: 'Santanópolis', uf_id: 5 },
        { id: 629, nome: 'Santo Amaro', uf_id: 5 },
        { id: 630, nome: 'Santo Antônio de Jesus', uf_id: 5 },
        { id: 631, nome: 'Santo Estêvão', uf_id: 5 },
        { id: 632, nome: 'São Desidério', uf_id: 5 },
        { id: 633, nome: 'São Domingos', uf_id: 5 },
        { id: 634, nome: 'São Felipe', uf_id: 5 },
        { id: 635, nome: 'São Félix', uf_id: 5 },
        { id: 636, nome: 'São Félix do Coribe', uf_id: 5 },
        { id: 637, nome: 'São Francisco do Conde', uf_id: 5 },
        { id: 638, nome: 'São Gabriel', uf_id: 5 },
        { id: 639, nome: 'São Gonçalo dos Campos', uf_id: 5 },
        { id: 640, nome: 'São José da Vitória', uf_id: 5 },
        { id: 641, nome: 'São José do Jacuípe', uf_id: 5 },
        { id: 642, nome: 'São Miguel das Matas', uf_id: 5 },
        { id: 643, nome: 'São Sebastião do Passé', uf_id: 5 },
        { id: 644, nome: 'Sapeaçu', uf_id: 5 },
        { id: 645, nome: 'Sátiro Dias', uf_id: 5 },
        { id: 646, nome: 'Saubara', uf_id: 5 },
        { id: 647, nome: 'Saúde', uf_id: 5 },
        { id: 648, nome: 'Seabra', uf_id: 5 },
        { id: 649, nome: 'Sebastião Laranjeiras', uf_id: 5 },
        { id: 650, nome: 'Senhor do Bonfim', uf_id: 5 },
        { id: 651, nome: 'Sento Sé', uf_id: 5 },
        { id: 652, nome: 'Serra do Ramalho', uf_id: 5 },
        { id: 653, nome: 'Serra Dourada', uf_id: 5 },
        { id: 654, nome: 'Serra Preta', uf_id: 5 },
        { id: 655, nome: 'Serrinha', uf_id: 5 },
        { id: 656, nome: 'Serrolândia', uf_id: 5 },
        { id: 657, nome: 'Simões Filho', uf_id: 5 },
        { id: 658, nome: 'Sítio do Mato', uf_id: 5 },
        { id: 659, nome: 'Sítio do Quinto', uf_id: 5 },
        { id: 660, nome: 'Sobradinho', uf_id: 5 },
        { id: 661, nome: 'Souto Soares', uf_id: 5 },
        { id: 662, nome: 'Tabocas do Brejo Velho', uf_id: 5 },
        { id: 663, nome: 'Tanhaçu', uf_id: 5 },
        { id: 664, nome: 'Tanque Novo', uf_id: 5 },
        { id: 665, nome: 'Tanquinho', uf_id: 5 },
        { id: 666, nome: 'Taperoá', uf_id: 5 },
        { id: 667, nome: 'Tapiramutá', uf_id: 5 },
        { id: 668, nome: 'Teixeira de Freitas', uf_id: 5 },
        { id: 669, nome: 'Teodoro Sampaio', uf_id: 5 },
        { id: 670, nome: 'Teofilândia', uf_id: 5 },
        { id: 671, nome: 'Teolândia', uf_id: 5 },
        { id: 672, nome: 'Terra Nova', uf_id: 5 },
        { id: 673, nome: 'Tremedal', uf_id: 5 },
        { id: 674, nome: 'Tucano', uf_id: 5 },
        { id: 675, nome: 'Uauá', uf_id: 5 },
        { id: 676, nome: 'Ubaíra', uf_id: 5 },
        { id: 677, nome: 'Ubaitaba', uf_id: 5 },
        { id: 678, nome: 'Ubatã', uf_id: 5 },
        { id: 679, nome: 'Uibaí', uf_id: 5 },
        { id: 680, nome: 'Umburanas', uf_id: 5 },
        { id: 681, nome: 'Una', uf_id: 5 },
        { id: 682, nome: 'Urandi', uf_id: 5 },
        { id: 683, nome: 'Uruçuca', uf_id: 5 },
        { id: 684, nome: 'Utinga', uf_id: 5 },
        { id: 685, nome: 'Valença', uf_id: 5 },
        { id: 686, nome: 'Valente', uf_id: 5 },
        { id: 687, nome: 'Várzea da Roça', uf_id: 5 },
        { id: 688, nome: 'Várzea do Poço', uf_id: 5 },
        { id: 689, nome: 'Várzea Nova', uf_id: 5 },
        { id: 690, nome: 'Varzedo', uf_id: 5 },
        { id: 691, nome: 'Vera Cruz', uf_id: 5 },
        { id: 692, nome: 'Vereda', uf_id: 5 },
        { id: 693, nome: 'Vitória da Conquista', uf_id: 5 },
        { id: 694, nome: 'Wagner', uf_id: 5 },
        { id: 695, nome: 'Wanderley', uf_id: 5 },
        { id: 696, nome: 'Wenceslau Guimarães', uf_id: 5 },
        { id: 697, nome: 'Xique-Xique', uf_id: 5 },
        { id: 698, nome: 'Abaiara', uf_id: 6 },
        { id: 699, nome: 'Acarape', uf_id: 6 },
        { id: 700, nome: 'Acaraú', uf_id: 6 },
        { id: 701, nome: 'Acopiara', uf_id: 6 },
        { id: 702, nome: 'Aiuaba', uf_id: 6 },
        { id: 703, nome: 'Alcântaras', uf_id: 6 },
        { id: 704, nome: 'Altaneira', uf_id: 6 },
        { id: 705, nome: 'Alto Santo', uf_id: 6 },
        { id: 706, nome: 'Amontada', uf_id: 6 },
        { id: 707, nome: 'Antonina do Norte', uf_id: 6 },
        { id: 708, nome: 'Apuiarés', uf_id: 6 },
        { id: 709, nome: 'Aquiraz', uf_id: 6 },
        { id: 710, nome: 'Aracati', uf_id: 6 },
        { id: 711, nome: 'Aracoiaba', uf_id: 6 },
        { id: 712, nome: 'Ararendá', uf_id: 6 },
        { id: 713, nome: 'Araripe', uf_id: 6 },
        { id: 714, nome: 'Aratuba', uf_id: 6 },
        { id: 715, nome: 'Arneiroz', uf_id: 6 },
        { id: 716, nome: 'Assaré', uf_id: 6 },
        { id: 717, nome: 'Aurora', uf_id: 6 },
        { id: 718, nome: 'Baixio', uf_id: 6 },
        { id: 719, nome: 'Banabuiú', uf_id: 6 },
        { id: 720, nome: 'Barbalha', uf_id: 6 },
        { id: 721, nome: 'Barreira', uf_id: 6 },
        { id: 722, nome: 'Barro', uf_id: 6 },
        { id: 723, nome: 'Barroquinha', uf_id: 6 },
        { id: 724, nome: 'Baturité', uf_id: 6 },
        { id: 725, nome: 'Beberibe', uf_id: 6 },
        { id: 726, nome: 'Bela Cruz', uf_id: 6 },
        { id: 727, nome: 'Boa Viagem', uf_id: 6 },
        { id: 728, nome: 'Brejo Santo', uf_id: 6 },
        { id: 729, nome: 'Camocim', uf_id: 6 },
        { id: 730, nome: 'Campos Sales', uf_id: 6 },
        { id: 731, nome: 'Canindé', uf_id: 6 },
        { id: 732, nome: 'Capistrano', uf_id: 6 },
        { id: 733, nome: 'Caridade', uf_id: 6 },
        { id: 734, nome: 'Cariré', uf_id: 6 },
        { id: 735, nome: 'Caririaçu', uf_id: 6 },
        { id: 736, nome: 'Cariús', uf_id: 6 },
        { id: 737, nome: 'Carnaubal', uf_id: 6 },
        { id: 738, nome: 'Cascavel', uf_id: 6 },
        { id: 739, nome: 'Catarina', uf_id: 6 },
        { id: 740, nome: 'Catunda', uf_id: 6 },
        { id: 741, nome: 'Caucaia', uf_id: 6 },
        { id: 742, nome: 'Cedro', uf_id: 6 },
        { id: 743, nome: 'Chaval', uf_id: 6 },
        { id: 744, nome: 'Choró', uf_id: 6 },
        { id: 745, nome: 'Chorozinho', uf_id: 6 },
        { id: 746, nome: 'Coreaú', uf_id: 6 },
        { id: 747, nome: 'Crateús', uf_id: 6 },
        { id: 748, nome: 'Crato', uf_id: 6 },
        { id: 749, nome: 'Croatá', uf_id: 6 },
        { id: 750, nome: 'Cruz', uf_id: 6 },
        { id: 751, nome: 'Deputado Irapuan Pinheiro', uf_id: 6 },
        { id: 752, nome: 'Ererê', uf_id: 6 },
        { id: 753, nome: 'Eusébio', uf_id: 6 },
        { id: 754, nome: 'Farias Brito', uf_id: 6 },
        { id: 755, nome: 'Forquilha', uf_id: 6 },
        { id: 756, nome: 'Fortaleza', uf_id: 6 },
        { id: 757, nome: 'Fortim', uf_id: 6 },
        { id: 758, nome: 'Frecheirinha', uf_id: 6 },
        { id: 759, nome: 'General Sampaio', uf_id: 6 },
        { id: 760, nome: 'Graça', uf_id: 6 },
        { id: 761, nome: 'Granja', uf_id: 6 },
        { id: 762, nome: 'Granjeiro', uf_id: 6 },
        { id: 763, nome: 'Groaíras', uf_id: 6 },
        { id: 764, nome: 'Guaiúba', uf_id: 6 },
        { id: 765, nome: 'Guaraciaba do Norte', uf_id: 6 },
        { id: 766, nome: 'Guaramiranga', uf_id: 6 },
        { id: 767, nome: 'Hidrolândia', uf_id: 6 },
        { id: 768, nome: 'Horizonte', uf_id: 6 },
        { id: 769, nome: 'Ibaretama', uf_id: 6 },
        { id: 770, nome: 'Ibiapina', uf_id: 6 },
        { id: 771, nome: 'Ibicuitinga', uf_id: 6 },
        { id: 772, nome: 'Icapuí', uf_id: 6 },
        { id: 773, nome: 'Icó', uf_id: 6 },
        { id: 774, nome: 'Iguatu', uf_id: 6 },
        { id: 775, nome: 'Independência', uf_id: 6 },
        { id: 776, nome: 'Ipaporanga', uf_id: 6 },
        { id: 777, nome: 'Ipaumirim', uf_id: 6 },
        { id: 778, nome: 'Ipu', uf_id: 6 },
        { id: 779, nome: 'Ipueiras', uf_id: 6 },
        { id: 780, nome: 'Iracema', uf_id: 6 },
        { id: 781, nome: 'Irauçuba', uf_id: 6 },
        { id: 782, nome: 'Itaiçaba', uf_id: 6 },
        { id: 783, nome: 'Itaitinga', uf_id: 6 },
        { id: 784, nome: 'Itapagé', uf_id: 6 },
        { id: 785, nome: 'Itapipoca', uf_id: 6 },
        { id: 786, nome: 'Itapiúna', uf_id: 6 },
        { id: 787, nome: 'Itarema', uf_id: 6 },
        { id: 788, nome: 'Itatira', uf_id: 6 },
        { id: 789, nome: 'Jaguaretama', uf_id: 6 },
        { id: 790, nome: 'Jaguaribara', uf_id: 6 },
        { id: 791, nome: 'Jaguaribe', uf_id: 6 },
        { id: 792, nome: 'Jaguaruana', uf_id: 6 },
        { id: 793, nome: 'Jardim', uf_id: 6 },
        { id: 794, nome: 'Jati', uf_id: 6 },
        { id: 795, nome: 'Jijoca de Jericoacoara', uf_id: 6 },
        { id: 796, nome: 'Juazeiro do Norte', uf_id: 6 },
        { id: 797, nome: 'Jucás', uf_id: 6 },
        { id: 798, nome: 'Lavras da Mangabeira', uf_id: 6 },
        { id: 799, nome: 'Limoeiro do Norte', uf_id: 6 },
        { id: 800, nome: 'Madalena', uf_id: 6 },
        { id: 801, nome: 'Maracanaú', uf_id: 6 },
        { id: 802, nome: 'Maranguape', uf_id: 6 },
        { id: 803, nome: 'Marco', uf_id: 6 },
        { id: 804, nome: 'Martinópole', uf_id: 6 },
        { id: 805, nome: 'Massapê', uf_id: 6 },
        { id: 806, nome: 'Mauriti', uf_id: 6 },
        { id: 807, nome: 'Meruoca', uf_id: 6 },
        { id: 808, nome: 'Milagres', uf_id: 6 },
        { id: 809, nome: 'Milhã', uf_id: 6 },
        { id: 810, nome: 'Miraíma', uf_id: 6 },
        { id: 811, nome: 'Missão Velha', uf_id: 6 },
        { id: 812, nome: 'Mombaça', uf_id: 6 },
        { id: 813, nome: 'Monsenhor Tabosa', uf_id: 6 },
        { id: 814, nome: 'Morada Nova', uf_id: 6 },
        { id: 815, nome: 'Moraújo', uf_id: 6 },
        { id: 816, nome: 'Morrinhos', uf_id: 6 },
        { id: 817, nome: 'Mucambo', uf_id: 6 },
        { id: 818, nome: 'Mulungu', uf_id: 6 },
        { id: 819, nome: 'Nova Olinda', uf_id: 6 },
        { id: 820, nome: 'Nova Russas', uf_id: 6 },
        { id: 821, nome: 'Novo Oriente', uf_id: 6 },
        { id: 822, nome: 'Ocara', uf_id: 6 },
        { id: 823, nome: 'Orós', uf_id: 6 },
        { id: 824, nome: 'Pacajus', uf_id: 6 },
        { id: 825, nome: 'Pacatuba', uf_id: 6 },
        { id: 826, nome: 'Pacoti', uf_id: 6 },
        { id: 827, nome: 'Pacujá', uf_id: 6 },
        { id: 828, nome: 'Palhano', uf_id: 6 },
        { id: 829, nome: 'Palmácia', uf_id: 6 },
        { id: 830, nome: 'Paracuru', uf_id: 6 },
        { id: 831, nome: 'Paraipaba', uf_id: 6 },
        { id: 832, nome: 'Parambu', uf_id: 6 },
        { id: 833, nome: 'Paramoti', uf_id: 6 },
        { id: 834, nome: 'Pedra Branca', uf_id: 6 },
        { id: 835, nome: 'Penaforte', uf_id: 6 },
        { id: 836, nome: 'Pentecoste', uf_id: 6 },
        { id: 837, nome: 'Pereiro', uf_id: 6 },
        { id: 838, nome: 'Pindoretama', uf_id: 6 },
        { id: 839, nome: 'Piquet Carneiro', uf_id: 6 },
        { id: 840, nome: 'Pires Ferreira', uf_id: 6 },
        { id: 841, nome: 'Poranga', uf_id: 6 },
        { id: 842, nome: 'Porteiras', uf_id: 6 },
        { id: 843, nome: 'Potengi', uf_id: 6 },
        { id: 844, nome: 'Potiretama', uf_id: 6 },
        { id: 845, nome: 'Quiterianópolis', uf_id: 6 },
        { id: 846, nome: 'Quixadá', uf_id: 6 },
        { id: 847, nome: 'Quixelô', uf_id: 6 },
        { id: 848, nome: 'Quixeramobim', uf_id: 6 },
        { id: 849, nome: 'Quixeré', uf_id: 6 },
        { id: 850, nome: 'Redenção', uf_id: 6 },
        { id: 851, nome: 'Reriutaba', uf_id: 6 },
        { id: 852, nome: 'Russas', uf_id: 6 },
        { id: 853, nome: 'Saboeiro', uf_id: 6 },
        { id: 854, nome: 'Salitre', uf_id: 6 },
        { id: 855, nome: 'Santa Quitéria', uf_id: 6 },
        { id: 856, nome: 'Santana do Acaraú', uf_id: 6 },
        { id: 857, nome: 'Santana do Cariri', uf_id: 6 },
        { id: 858, nome: 'São Benedito', uf_id: 6 },
        { id: 859, nome: 'São Gonçalo do Amarante', uf_id: 6 },
        { id: 860, nome: 'São João do Jaguaribe', uf_id: 6 },
        { id: 861, nome: 'São Luís do Curu', uf_id: 6 },
        { id: 862, nome: 'Senador Pompeu', uf_id: 6 },
        { id: 863, nome: 'Senador Sá', uf_id: 6 },
        { id: 864, nome: 'Sobral', uf_id: 6 },
        { id: 865, nome: 'Solonópole', uf_id: 6 },
        { id: 866, nome: 'Tabuleiro do Norte', uf_id: 6 },
        { id: 867, nome: 'Tamboril', uf_id: 6 },
        { id: 868, nome: 'Tarrafas', uf_id: 6 },
        { id: 869, nome: 'Tauá', uf_id: 6 },
        { id: 870, nome: 'Tejuçuoca', uf_id: 6 },
        { id: 871, nome: 'Tianguá', uf_id: 6 },
        { id: 872, nome: 'Trairi', uf_id: 6 },
        { id: 873, nome: 'Tururu', uf_id: 6 },
        { id: 874, nome: 'Ubajara', uf_id: 6 },
        { id: 875, nome: 'Umari', uf_id: 6 },
        { id: 876, nome: 'Umirim', uf_id: 6 },
        { id: 877, nome: 'Uruburetama', uf_id: 6 },
        { id: 878, nome: 'Uruoca', uf_id: 6 },
        { id: 879, nome: 'Varjota', uf_id: 6 },
        { id: 880, nome: 'Várzea Alegre', uf_id: 6 },
        { id: 881, nome: 'Viçosa do Ceará', uf_id: 6 },
        { id: 882, nome: 'Brasília', uf_id: 7 },
        { id: 883, nome: 'Abadia de Goiás', uf_id: 9 },
        { id: 884, nome: 'Abadiânia', uf_id: 9 },
        { id: 885, nome: 'Acreúna', uf_id: 9 },
        { id: 886, nome: 'Adelândia', uf_id: 9 },
        { id: 887, nome: 'Água Fria de Goiás', uf_id: 9 },
        { id: 888, nome: 'Água Limpa', uf_id: 9 },
        { id: 889, nome: 'Águas Lindas de Goiás', uf_id: 9 },
        { id: 890, nome: 'Alexânia', uf_id: 9 },
        { id: 891, nome: 'Aloândia', uf_id: 9 },
        { id: 892, nome: 'Alto Horizonte', uf_id: 9 },
        { id: 893, nome: 'Alto Paraíso de Goiás', uf_id: 9 },
        { id: 894, nome: 'Alvorada do Norte', uf_id: 9 },
        { id: 895, nome: 'Amaralina', uf_id: 9 },
        { id: 896, nome: 'Americano do Brasil', uf_id: 9 },
        { id: 897, nome: 'Amorinópolis', uf_id: 9 },
        { id: 898, nome: 'Anápolis', uf_id: 9 },
        { id: 899, nome: 'Anhanguera', uf_id: 9 },
        { id: 900, nome: 'Anicuns', uf_id: 9 },
        { id: 901, nome: 'Aparecida de Goiânia', uf_id: 9 },
        { id: 902, nome: 'Aparecida do Rio Doce', uf_id: 9 },
        { id: 903, nome: 'Aporé', uf_id: 9 },
        { id: 904, nome: 'Araçu', uf_id: 9 },
        { id: 905, nome: 'Aragarças', uf_id: 9 },
        { id: 906, nome: 'Aragoiânia', uf_id: 9 },
        { id: 907, nome: 'Araguapaz', uf_id: 9 },
        { id: 908, nome: 'Arenópolis', uf_id: 9 },
        { id: 909, nome: 'Aruanã', uf_id: 9 },
        { id: 910, nome: 'Aurilândia', uf_id: 9 },
        { id: 911, nome: 'Avelinópolis', uf_id: 9 },
        { id: 912, nome: 'Baliza', uf_id: 9 },
        { id: 913, nome: 'Barro Alto', uf_id: 9 },
        { id: 914, nome: 'Bela Vista de Goiás', uf_id: 9 },
        { id: 915, nome: 'Bom Jardim de Goiás', uf_id: 9 },
        { id: 916, nome: 'Bom Jesus de Goiás', uf_id: 9 },
        { id: 917, nome: 'Bonfinópolis', uf_id: 9 },
        { id: 918, nome: 'Bonópolis', uf_id: 9 },
        { id: 919, nome: 'Brazabrantes', uf_id: 9 },
        { id: 920, nome: 'Britânia', uf_id: 9 },
        { id: 921, nome: 'Buriti Alegre', uf_id: 9 },
        { id: 922, nome: 'Buriti de Goiás', uf_id: 9 },
        { id: 923, nome: 'Buritinópolis', uf_id: 9 },
        { id: 924, nome: 'Cabeceiras', uf_id: 9 },
        { id: 925, nome: 'Cachoeira Alta', uf_id: 9 },
        { id: 926, nome: 'Cachoeira de Goiás', uf_id: 9 },
        { id: 927, nome: 'Cachoeira Dourada', uf_id: 9 },
        { id: 928, nome: 'Caçu', uf_id: 9 },
        { id: 929, nome: 'Caiapônia', uf_id: 9 },
        { id: 930, nome: 'Caldas Novas', uf_id: 9 },
        { id: 931, nome: 'Caldazinha', uf_id: 9 },
        { id: 932, nome: 'Campestre de Goiás', uf_id: 9 },
        { id: 933, nome: 'Campinaçu', uf_id: 9 },
        { id: 934, nome: 'Campinorte', uf_id: 9 },
        { id: 935, nome: 'Campo Alegre de Goiás', uf_id: 9 },
        { id: 936, nome: 'Campo Limpo de Goiás', uf_id: 9 },
        { id: 937, nome: 'Campos Belos', uf_id: 9 },
        { id: 938, nome: 'Campos Verdes', uf_id: 9 },
        { id: 939, nome: 'Carmo do Rio Verde', uf_id: 9 },
        { id: 940, nome: 'Castelândia', uf_id: 9 },
        { id: 941, nome: 'Catalão', uf_id: 9 },
        { id: 942, nome: 'Caturaí', uf_id: 9 },
        { id: 943, nome: 'Cavalcante', uf_id: 9 },
        { id: 944, nome: 'Ceres', uf_id: 9 },
        { id: 945, nome: 'Cezarina', uf_id: 9 },
        { id: 946, nome: 'Chapadão do Céu', uf_id: 9 },
        { id: 947, nome: 'Cidade Ocidental', uf_id: 9 },
        { id: 948, nome: 'Cocalzinho de Goiás', uf_id: 9 },
        { id: 949, nome: 'Colinas do Sul', uf_id: 9 },
        { id: 950, nome: 'Córrego do Ouro', uf_id: 9 },
        { id: 951, nome: 'Corumbá de Goiás', uf_id: 9 },
        { id: 952, nome: 'Corumbaíba', uf_id: 9 },
        { id: 953, nome: 'Cristalina', uf_id: 9 },
        { id: 954, nome: 'Cristianópolis', uf_id: 9 },
        { id: 955, nome: 'Crixás', uf_id: 9 },
        { id: 956, nome: 'Cromínia', uf_id: 9 },
        { id: 957, nome: 'Cumari', uf_id: 9 },
        { id: 958, nome: 'Damianópolis', uf_id: 9 },
        { id: 959, nome: 'Damolândia', uf_id: 9 },
        { id: 960, nome: 'Davinópolis', uf_id: 9 },
        { id: 961, nome: 'Diorama', uf_id: 9 },
        { id: 962, nome: 'Divinópolis de Goiás', uf_id: 9 },
        { id: 963, nome: 'Doverlândia', uf_id: 9 },
        { id: 964, nome: 'Edealina', uf_id: 9 },
        { id: 965, nome: 'Edéia', uf_id: 9 },
        { id: 966, nome: 'Estrela do Norte', uf_id: 9 },
        { id: 967, nome: 'Faina', uf_id: 9 },
        { id: 968, nome: 'Fazenda Nova', uf_id: 9 },
        { id: 969, nome: 'Firminópolis', uf_id: 9 },
        { id: 970, nome: 'Flores de Goiás', uf_id: 9 },
        { id: 971, nome: 'Formosa', uf_id: 9 },
        { id: 972, nome: 'Formoso', uf_id: 9 },
        { id: 973, nome: 'Gameleira de Goiás', uf_id: 9 },
        { id: 974, nome: 'Goianápolis', uf_id: 9 },
        { id: 975, nome: 'Goiandira', uf_id: 9 },
        { id: 976, nome: 'Goianésia', uf_id: 9 },
        { id: 977, nome: 'Goiânia', uf_id: 9 },
        { id: 978, nome: 'Goianira', uf_id: 9 },
        { id: 979, nome: 'Goiás', uf_id: 9 },
        { id: 980, nome: 'Goiatuba', uf_id: 9 },
        { id: 981, nome: 'Gouvelândia', uf_id: 9 },
        { id: 982, nome: 'Guapó', uf_id: 9 },
        { id: 983, nome: 'Guaraíta', uf_id: 9 },
        { id: 984, nome: 'Guarani de Goiás', uf_id: 9 },
        { id: 985, nome: 'Guarinos', uf_id: 9 },
        { id: 986, nome: 'Heitoraí', uf_id: 9 },
        { id: 987, nome: 'Hidrolândia', uf_id: 9 },
        { id: 988, nome: 'Hidrolina', uf_id: 9 },
        { id: 989, nome: 'Iaciara', uf_id: 9 },
        { id: 990, nome: 'Inaciolândia', uf_id: 9 },
        { id: 991, nome: 'Indiara', uf_id: 9 },
        { id: 992, nome: 'Inhumas', uf_id: 9 },
        { id: 993, nome: 'Ipameri', uf_id: 9 },
        { id: 994, nome: 'Ipiranga de Goiás', uf_id: 9 },
        { id: 995, nome: 'Iporá', uf_id: 9 },
        { id: 996, nome: 'Israelândia', uf_id: 9 },
        { id: 997, nome: 'Itaberaí', uf_id: 9 },
        { id: 998, nome: 'Itaguari', uf_id: 9 },
        { id: 999, nome: 'Itaguaru', uf_id: 9 }
    ])
}