import knex from 'knex';

export async function seed(knex: knex.Knex) {
    await knex('cidade').insert([
        { id: 5500, nome: 'Maurilândia do Tocantins', uf_id: 27 },
        { id: 5501, nome: 'Miracema do Tocantins', uf_id: 27 },
        { id: 5502, nome: 'Miranorte', uf_id: 27 },
        { id: 5503, nome: 'Monte do Carmo', uf_id: 27 },
        { id: 5504, nome: 'Monte Santo do Tocantins', uf_id: 27 },
        { id: 5505, nome: 'Muricilândia', uf_id: 27 },
        { id: 5506, nome: 'Natividade', uf_id: 27 },
        { id: 5507, nome: 'Nazaré', uf_id: 27 },
        { id: 5508, nome: 'Nova Olinda', uf_id: 27 },
        { id: 5509, nome: 'Nova Rosalândia', uf_id: 27 },
        { id: 5510, nome: 'Novo Acordo', uf_id: 27 },
        { id: 5511, nome: 'Novo Alegre', uf_id: 27 },
        { id: 5512, nome: 'Novo Jardim', uf_id: 27 },
        { id: 5513, nome: 'Oliveira de Fátima', uf_id: 27 },
        { id: 5514, nome: 'Palmas', uf_id: 27 },
        { id: 5515, nome: 'Palmeirante', uf_id: 27 },
        { id: 5516, nome: 'Palmeiras do Tocantins', uf_id: 27 },
        { id: 5517, nome: 'Palmeirópolis', uf_id: 27 },
        { id: 5518, nome: 'Paraíso do Tocantins', uf_id: 27 },
        { id: 5519, nome: 'Paranã', uf_id: 27 },
        { id: 5520, nome: 'Pau d`Arco', uf_id: 27 },
        { id: 5521, nome: 'Pedro Afonso', uf_id: 27 },
        { id: 5522, nome: 'Peixe', uf_id: 27 },
        { id: 5523, nome: 'Pequizeiro', uf_id: 27 },
        { id: 5524, nome: 'Pindorama do Tocantins', uf_id: 27 },
        { id: 5525, nome: 'Piraquê', uf_id: 27 },
        { id: 5526, nome: 'Pium', uf_id: 27 },
        { id: 5527, nome: 'Ponte Alta do Bom Jesus', uf_id: 27 },
        { id: 5528, nome: 'Ponte Alta do Tocantins', uf_id: 27 },
        { id: 5529, nome: 'Porto Alegre do Tocantins', uf_id: 27 },
        { id: 5530, nome: 'Porto Nacional', uf_id: 27 },
        { id: 5531, nome: 'Praia Norte', uf_id: 27 },
        { id: 5532, nome: 'Presidente Kennedy', uf_id: 27 },
        { id: 5533, nome: 'Pugmil', uf_id: 27 },
        { id: 5534, nome: 'Recursolândia', uf_id: 27 },
        { id: 5535, nome: 'Riachinho', uf_id: 27 },
        { id: 5536, nome: 'Rio da Conceição', uf_id: 27 },
        { id: 5537, nome: 'Rio dos Bois', uf_id: 27 },
        { id: 5538, nome: 'Rio Sono', uf_id: 27 },
        { id: 5539, nome: 'Sampaio', uf_id: 27 },
        { id: 5540, nome: 'Sandolândia', uf_id: 27 },
        { id: 5541, nome: 'Santa Fé do Araguaia', uf_id: 27 },
        { id: 5542, nome: 'Santa Maria do Tocantins', uf_id: 27 },
        { id: 5543, nome: 'Santa Rita do Tocantins', uf_id: 27 },
        { id: 5544, nome: 'Santa Rosa do Tocantins', uf_id: 27 },
        { id: 5545, nome: 'Santa Tereza do Tocantins', uf_id: 27 },
        { id: 5546, nome: 'Santa Terezinha do Tocantins', uf_id: 27 },
        { id: 5547, nome: 'São Bento do Tocantins', uf_id: 27 },
        { id: 5548, nome: 'São Félix do Tocantins', uf_id: 27 },
        { id: 5549, nome: 'São Miguel do Tocantins', uf_id: 27 },
        { id: 5550, nome: 'São Salvador do Tocantins', uf_id: 27 },
        { id: 5551, nome: 'São Sebastião do Tocantins', uf_id: 27 },
        { id: 5552, nome: 'São Valério da Natividade', uf_id: 27 },
        { id: 5553, nome: 'Silvanópolis', uf_id: 27 },
        { id: 5554, nome: 'Sítio Novo do Tocantins', uf_id: 27 },
        { id: 5555, nome: 'Sucupira', uf_id: 27 },
        { id: 5556, nome: 'Taguatinga', uf_id: 27 },
        { id: 5557, nome: 'Taipas do Tocantins', uf_id: 27 },
        { id: 5558, nome: 'Talismã', uf_id: 27 },
        { id: 5559, nome: 'Tocantínia', uf_id: 27 },
        { id: 5560, nome: 'Tocantinópolis', uf_id: 27 },
        { id: 5561, nome: 'Tupirama', uf_id: 27 },
        { id: 5562, nome: 'Tupiratins', uf_id: 27 },
        { id: 5563, nome: 'Wanderlândia', uf_id: 27 },
        { id: 5564, nome: 'Xambioá', uf_id: 27 },
        { id: 5575, nome: 'Gama', uf_id: 7 },
        { id: 5576, nome: 'Taguatinga', uf_id: 7 },
        { id: 5577, nome: 'Brazlândia', uf_id: 7 },
        { id: 5578, nome: 'Sobradinho', uf_id: 7 },
        { id: 5579, nome: 'Planaltina', uf_id: 7 },
        { id: 5580, nome: 'Paranoá', uf_id: 7 },
        { id: 5581, nome: 'Núcleo Bandeirante', uf_id: 7 },
        { id: 5582, nome: 'Ceilândia', uf_id: 7 },
        { id: 5583, nome: 'Guará', uf_id: 7 },
        { id: 5584, nome: 'Cruzeiro', uf_id: 7 },
        { id: 5585, nome: 'Samambaia', uf_id: 7 },
        { id: 5586, nome: 'Santa Maria', uf_id: 7 },
        { id: 5587, nome: 'São Sebastião', uf_id: 7 },
        { id: 5589, nome: 'Lago Sul', uf_id: 7 },
        { id: 5590, nome: 'Riacho Fundo', uf_id: 7 },
        { id: 5591, nome: 'Lago Norte', uf_id: 7 },
        { id: 5592, nome: 'Candangolândia', uf_id: 7 },
        { id: 5593, nome: 'Águas Claras', uf_id: 7 },
        { id: 5594, nome: 'Riacho Fundo II', uf_id: 7 },
        { id: 5595, nome: 'Sudoeste/Octogonal', uf_id: 7 },
        { id: 5596, nome: 'Varjão', uf_id: 7 },
        { id: 5597, nome: 'Park Way', uf_id: 7 },
        { id: 5598, nome: 'SCIA', uf_id: 7 },
        { id: 5599, nome: 'Sobradinho II', uf_id: 7 },
        { id: 5601, nome: 'Itapoã', uf_id: 7 },
        { id: 5602, nome: 'SIA', uf_id: 7 },
        { id: 5603, nome: 'Vicente Pires', uf_id: 7 },
        { id: 5604, nome: 'Fercal', uf_id: 7 },
        { id: 5574, nome: 'Recanto das Emas', uf_id: 7 },
        { id: 5600, nome: 'Jardim Botânico', uf_id: 7 },
        { id: 5605, nome: 'Nazária', uf_id: 17 },
        { id: 5606, nome: 'Paraíso das Águas', uf_id: 12 },
        { id: 5607, nome: 'Pinto Bandeira', uf_id: 23 },
        { id: 5608, nome: 'Balneário Rincão', uf_id: 24 },
        { id: 5609, nome: 'Pescaria Brava', uf_id: 24 }
    ])
}